@startuml
skinparam classAttributeIconSize 0

package Controllers {

    class EmployeeController {
        - repository : EmployeeRepository
        + EmployeeController(repository : EmployeeRepository)
        + all() : <Employee>
        + newEmployee(newEmployee : Employee) : Employee
        + one(id : long) : Employee
        + replaceEmployee(newEmployee : Employee, id : long) : Employee
        + deleteEmployee(id : long) : void
    }

    class EmployeeNotFoundAdvice {
        + employeeNotFoundHandler(ex : EmployeeNotFoundException) : string
    }

    class EmployeeNotFoundException {
        + EmployeeNotFoundException(id : long)
    }

    class DepartmentController {
        - repository : DepartmentRepository
        + DepartmentController(repository : DepartmentRepository)
        + all() : <Department>
        + newDepartment(newDepartment : Department) : Department
        + one(name : string) : Department
        + deleteDepartment(name : string) : void
    }
}

package Entities {
    class Employee {
        - email : string
        - name : string
        - role : string
        - department : Department
        + Employee()
        + Employee(email : string, name : string, role : string, department : Department)
        + getEmail() : string
        + setEmail(email : string) : void
        + getName() : string
        + setName(name : string) : void
        + getRole() : string
        + setRole(role : string) : void
        + getDepartment() : Department
        + setDepartment(department : Department) : void
        + equals(o : Object) : boolean
        + hashCode() : int
        + toString() : string
    }

    class Department {
        - name : string
        + Department()
        + Department(name : string)
        + getName() : string
        + setName(name : string) : void
        + equals(o : Object) : boolean
        + hashCode() : int
        + toString() : string
    }
}

package Repositories {
    interface EmployeeRepository {
    }

    interface DepartmentRepository {
    }
}

EmployeeController --> EmployeeRepository
EmployeeController --> Employee
EmployeeNotFoundAdvice --> EmployeeNotFoundException
EmployeeNotFoundException --> EmployeeController
EmployeeRepository ..> JpaRepository : extends
EmployeeNotFoundException ..> RuntimeException : extends

DepartmentController --> DepartmentRepository
DepartmentController --> Department
DepartmentRepository ..> JpaRepository : extends

Employee "1" --> "1" Department
Department "1" --> "*" Employee

@enduml
