@startuml
skinparam classAttributeIconSize 0
package Controllers {

    class EmployeeController {
        - repository : EmployeeRepository
        + EmployeeController(repository : EmployeeRepository)
        + all() : <Employee>
        + newEmployee(newEmployee : Employee) : Employee
        + one(id : long) : Employee
        + replaceEmployee(newEmployee : Employee, id : long) : Employee
        + deleteEmployee(id : long) : void
    }

    class EmployeeNotFoundAdvice {
        + employeeNotFoundHandler(ex : EmployeeNotFoundException) : string
    }

    class EmployeeNotFoundException {
        + EmployeeNotFoundException(id : long)
    }
}

package Entities {
    class Employee {
        - id : long
        - name : string
        - role : string
        + Employee()
        + Employee(name : string , role : string)
        + getID() : long
        + setId(id : long) : void
        + getName() : string
        + setName(name : string) : void
        + getRole() : string
        + setRole(role : string) : void
        + equals(o : Object) : boolean
        + hashCode() : int
        + toString() : string
    }
}

package Repositories {
    interface EmployeeRepository {
    }
}

EmployeeController --> EmployeeRepository
EmployeeController --> Employee
EmployeeNotFoundAdvice --> EmployeeNotFoundException
EmployeeNotFoundException --> EmployeeController
EmployeeRepository ..> JpaRepository : extends
EmployeeNotFoundException ..> RuntimeException : extends

@enduml
